"""add_income_installment_columns

Revision ID: 5c2e9bc13f63
Revises: None
Create Date: 2026-06-28 00:34:30.726434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c2e9bc13f63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('expense_category_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('expense_category_id')
    )
    op.create_index(op.f('ix_expense_categories_expense_category_id'), 'expense_categories', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_expense_categories_user_id'), 'expense_categories', ['user_id'], unique=False)
    op.create_index('uq_expense_category_user_name_active', 'expense_categories', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('income_categories',
    sa.Column('income_category_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('income_category_id')
    )
    op.create_index(op.f('ix_income_categories_income_category_id'), 'income_categories', ['income_category_id'], unique=False)
    op.create_index(op.f('ix_income_categories_user_id'), 'income_categories', ['user_id'], unique=False)
    op.create_index('uq_income_category_user_name_active', 'income_categories', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'PIX', 'BANK_TRANSFER', name='paymentmethodtype'), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_method_id')
    )
    op.create_index(op.f('ix_payment_methods_payment_method_id'), 'payment_methods', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_index('uq_payment_method_user_name_active', 'payment_methods', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('expenses',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expense_category_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_group_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='expensestatus'), nullable=False),
    sa.Column('installment_current', sa.Integer(), nullable=False),
    sa.Column('installment_total', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.expense_category_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expenses_transaction_group_id'), 'expenses', ['transaction_group_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('incomes',
    sa.Column('income_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('income_category_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_group_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'RECEIVED', name='incomestatus'), nullable=False),
    sa.Column('installment_current', sa.Integer(), nullable=False),
    sa.Column('installment_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['income_category_id'], ['income_categories.income_category_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('income_id')
    )
    op.create_index(op.f('ix_incomes_date'), 'incomes', ['date'], unique=False)
    op.create_index(op.f('ix_incomes_income_id'), 'incomes', ['income_id'], unique=False)
    op.create_index(op.f('ix_incomes_transaction_group_id'), 'incomes', ['transaction_group_id'], unique=False)
    op.create_index(op.f('ix_incomes_user_id'), 'incomes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomes_user_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_transaction_group_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_income_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_date'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_transaction_group_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('uq_payment_method_user_name_active', table_name='payment_methods', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_payment_method_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('uq_income_category_user_name_active', table_name='income_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_income_categories_user_id'), table_name='income_categories')
    op.drop_index(op.f('ix_income_categories_income_category_id'), table_name='income_categories')
    op.drop_table('income_categories')
    op.drop_index('uq_expense_category_user_name_active', table_name='expense_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_expense_categories_user_id'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_expense_category_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
